---
# Generic NFS playbook.
# This needs the nfs_mounts list variable, either from a var file or something like AWX. 
- name: Connect the vm to the Media share on Truenas
  hosts: nfs_client_media
  roles:
  - role: nfs_client
